apiVersion: v1
kind: Service
metadata:
  name: simple-service
spec:
  selector:                  
    app: counter
  ports:
  - nodePort: 0
    port: 5000               
    protocol: TCP
    targetPort: 5000
labels:
  app: counter
